default: &default
  adapter: mysql2
  encoding: utf8
  database: donart_dev
  pool: 5
  timeout: 5000
  username: root
  password:
  socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
test:
  <<: *default
  database: donart_test


production:
  adapter: postgresql
  encoding: unicode
  database: dfvl642u9eut4a
  port: 5432
  pool: 5
